# Conda environment for SARIAD development
name: SARIAD

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio
  - pytorch-lightning=2.5.0.post0
  - cuda-toolkit=12.4  
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.7.0
  - scikit-learn=1.6.0
  - opencv
  - pillow=11.1.0
  - tqdm=4.67.1
  - scipy=1.15.0
  - sympy=1.13.1
  - networkx=3.4.2
  - joblib=1.4.2
  - pyyaml=6.0.2
  - regex=2024.11.6
  - requests=2.32.3
  - protobuf
  - lightning-utilities=0.11.9
  - pip:
    - anomalib==1.2.0  
    - FrEIA==0.2
    - einops==0.8.0
    - huggingface-hub==0.27.0
    - timm==1.0.12
    - open_clip_torch==2.30.0
    - gdown==5.2.0
    - shapely==2.0.6
    - safetensors==0.5.0
    - rich==13.9.4
    - jsonargparse==4.35.0
    - tensorboard
    - comet_ml  
