# SARIAD Experiment Configuration
# This file defines the datasets, models, preprocessors, and runs to execute.

# Global settings
seed: 42
output_dir: "results"

experiments:
  - name: "Padim_on_MSTAR_without_preproc"
    dataset: SSDD
    preprocessor: null
    model: Padim
    runs: 2

  - name: "Padim_on_MSTAR_with_NLM_preproc"
    dataset: SSDD
    preprocessor: NLM
    model: Padim
    runs: 2

  - name: "Padim_on_MSTAR_with_MF_preproc"
    dataset: SSDD
    preprocessor: MedianFilter
    model: Padim
    runs: 2

datasets:
  MSTAR:
    batch_size: 32
  HRSID:
    batch_size: 16
  SSDD:
    batch_size: 16

models:
  Padim: null
    
preprocessors:
  NLM: null
  MedianFilter: null
